const data = [
    { "label": "NIKE", "value": 1 },
    { "label": "ADIDAS", "value": 2 },
    { "label": "GUCCI", "value": 3 },
    { "label": "ZARA", "value": 4 },
    { "label": "H&M", "value": 5 },
    { "label": "LOUIS VUITTON", "value": 6 },
    { "label": "CHANEL", "value": 7 },
    { "label": "VERSACE", "value": 8 },
    { "label": "PUMA", "value": 9 },
    { "label": "FILA", "value": 10 },
    { "label": "BURBERRY", "value": 11 },
    { "label": "CALVIN KLEIN", "value": 12 },
    { "label": "RALPH LAUREN", "value": 13 },
    { "label": "TOMMY HILFIGER", "value": 14 },
    { "label": "VANS", "value": 15 },
    { "label": "CONVERSE", "value": 16 },
    { "label": "LEVI'S", "value": 17 },
    { "label": "UNDER ARMOUR", "value": 18 },
    { "label": "COACH", "value": 19 },
    { "label": "MICHAEL KORS", "value": 20 },
    { "label": "DKNY", "value": 21 },
    { "label": "HOLLISTER", "value": 22 },
    { "label": "AEROPOSTALE", "value": 23 },
    { "label": "TIMBERLAND", "value": 24 },
    { "label": "VICTORIA'S SECRET", "value": 25 },
    { "label": "GAP", "value": 26 },
    { "label": "PINK", "value": 27 },
    { "label": "SUPREME", "value": 28 },
    { "label": "THE NORTH FACE", "value": 29 },
    { "label": "COLUMBIA", "value": 30 },
    { "label": "CHAMPION", "value": 31 },
    { "label": "PACSUN", "value": 32 },
    { "label": "ASOS", "value": 33 },
    { "label": "URBAN OUTFITTERS", "value": 34 },
    { "label": "FOREVER 21", "value": 35 },
    { "label": "HUGO BOSS", "value": 36 },
    { "label": "FENDI", "value": 37 },
    { "label": "BALENCIAGA", "value": 38 },
    { "label": "DOLCE & GABBANA", "value": 39 },
    { "label": "GUESS", "value": 40 },
    { "label": "VERSUS VERSACE", "value": 41 },
    { "label": "OFF-WHITE", "value": 42 },
    { "label": "BALMAIN", "value": 43 },
    { "label": "KENZO", "value": 44 },
    { "label": "SAINT LAURENT", "value": 45 },
    { "label": "VALENTINO", "value": 46 },
    { "label": "MANGO", "value": 47 },
    { "label": "MARC JACOBS", "value": 48 },
    { "label": "PRADA", "value": 49 },
    { "label": "DIESEL", "value": 50 },
    {"label": "JORDAN", "value": 51},
    {"label": "AMIRI", "value": 52}
];
export default data;