export default {
    "location": {
      "name": "Hillside",
      "region": "New Jersey",
      "country": "United States of America",
      "lat": 40.71,
      "lon": -74.23,
      "tz_id": "America/New_York",
      "localtime_epoch": 1694372579,
      "localtime": "2023-09-10 15:02"
    },
    "forecast": {
      "forecastday": [
        {
          "date": "2023-08-23",
          "date_epoch": 1692748800,
          "day": {
            "maxtemp_c": 26.4,
            "maxtemp_f": 79.5,
            "mintemp_c": 17.7,
            "mintemp_f": 63.9,
            "avgtemp_c": 21.7,
            "avgtemp_f": 71.0,
            "maxwind_mph": 9.2,
            "maxwind_kph": 14.8,
            "totalprecip_mm": 0.0,
            "totalprecip_in": 0.0,
            "avgvis_km": 10.0,
            "avgvis_miles": 6.0,
            "avghumidity": 49.0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "uv": 6.0
          },
          "astro": {
            "sunrise": "06:15 AM",
            "sunset": "07:44 PM",
            "moonrise": "01:21 PM",
            "moonset": "11:03 PM",
            "moon_phase": "Waxing Crescent",
            "moon_illumination": "36"
          },
          "hour": [
            {
              "time_epoch": 1692763200,
              "time": "2023-08-23 00:00",
              "temp_c": 20.6,
              "temp_f": 69.1,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 318,
              "wind_dir": "NW",
              "pressure_mb": 1019.0,
              "pressure_in": 30.1,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 50,
              "cloud": 22,
              "feelslike_c": 20.6,
              "feelslike_f": 69.1,
              "windchill_c": 20.6,
              "windchill_f": 69.1,
              "heatindex_c": 20.6,
              "heatindex_f": 69.1,
              "dewpoint_c": 9.8,
              "dewpoint_f": 49.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.3,
              "gust_kph": 14.9,
              "uv": 1.0
            },
            {
              "time_epoch": 1692766800,
              "time": "2023-08-23 01:00",
              "temp_c": 20.1,
              "temp_f": 68.2,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4.5,
              "wind_kph": 7.2,
              "wind_degree": 340,
              "wind_dir": "NNW",
              "pressure_mb": 1020.0,
              "pressure_in": 30.11,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 50,
              "cloud": 28,
              "feelslike_c": 20.1,
              "feelslike_f": 68.2,
              "windchill_c": 20.1,
              "windchill_f": 68.2,
              "heatindex_c": 20.1,
              "heatindex_f": 68.2,
              "dewpoint_c": 9.5,
              "dewpoint_f": 49.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.8,
              "gust_kph": 15.8,
              "uv": 1.0
            },
            {
              "time_epoch": 1692770400,
              "time": "2023-08-23 02:00",
              "temp_c": 19.0,
              "temp_f": 66.2,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 5.1,
              "wind_kph": 8.3,
              "wind_degree": 4,
              "wind_dir": "N",
              "pressure_mb": 1018.0,
              "pressure_in": 30.07,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 72,
              "cloud": 0,
              "feelslike_c": 19.0,
              "feelslike_f": 66.2,
              "windchill_c": 19.0,
              "windchill_f": 66.2,
              "heatindex_c": 19.0,
              "heatindex_f": 66.2,
              "dewpoint_c": 13.8,
              "dewpoint_f": 56.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 10.5,
              "gust_kph": 16.9,
              "uv": 1.0
            },
            {
              "time_epoch": 1692774000,
              "time": "2023-08-23 03:00",
              "temp_c": 19.3,
              "temp_f": 66.7,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 21,
              "wind_dir": "NNE",
              "pressure_mb": 1020.0,
              "pressure_in": 30.11,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 56,
              "cloud": 33,
              "feelslike_c": 19.3,
              "feelslike_f": 66.7,
              "windchill_c": 19.3,
              "windchill_f": 66.7,
              "heatindex_c": 19.3,
              "heatindex_f": 66.7,
              "dewpoint_c": 10.2,
              "dewpoint_f": 50.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.6,
              "gust_kph": 15.5,
              "uv": 1.0
            },
            {
              "time_epoch": 1692777600,
              "time": "2023-08-23 04:00",
              "temp_c": 18.9,
              "temp_f": 66.0,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 22,
              "wind_dir": "NNE",
              "pressure_mb": 1020.0,
              "pressure_in": 30.12,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 57,
              "cloud": 30,
              "feelslike_c": 18.9,
              "feelslike_f": 66.0,
              "windchill_c": 18.9,
              "windchill_f": 66.0,
              "heatindex_c": 18.9,
              "heatindex_f": 66.0,
              "dewpoint_c": 10.2,
              "dewpoint_f": 50.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.6,
              "gust_kph": 15.5,
              "uv": 1.0
            },
            {
              "time_epoch": 1692781200,
              "time": "2023-08-23 05:00",
              "temp_c": 17.7,
              "temp_f": 63.9,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 6.7,
              "wind_kph": 10.8,
              "wind_degree": 20,
              "wind_dir": "NNE",
              "pressure_mb": 1019.0,
              "pressure_in": 30.09,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 76,
              "cloud": 0,
              "feelslike_c": 17.7,
              "feelslike_f": 63.9,
              "windchill_c": 17.7,
              "windchill_f": 63.9,
              "heatindex_c": 17.7,
              "heatindex_f": 63.9,
              "dewpoint_c": 13.5,
              "dewpoint_f": 56.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 10.1,
              "gust_kph": 16.2,
              "uv": 1.0
            },
            {
              "time_epoch": 1692784800,
              "time": "2023-08-23 06:00",
              "temp_c": 18.0,
              "temp_f": 64.4,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 15,
              "wind_dir": "NNE",
              "pressure_mb": 1020.0,
              "pressure_in": 30.12,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 58,
              "cloud": 26,
              "feelslike_c": 18.0,
              "feelslike_f": 64.4,
              "windchill_c": 18.0,
              "windchill_f": 64.4,
              "heatindex_c": 18.0,
              "heatindex_f": 64.4,
              "dewpoint_c": 9.5,
              "dewpoint_f": 49.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.8,
              "gust_kph": 15.8,
              "uv": 1.0
            },
            {
              "time_epoch": 1692788400,
              "time": "2023-08-23 07:00",
              "temp_c": 17.9,
              "temp_f": 64.2,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 14,
              "wind_dir": "NNE",
              "pressure_mb": 1021.0,
              "pressure_in": 30.14,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 56,
              "cloud": 21,
              "feelslike_c": 17.9,
              "feelslike_f": 64.2,
              "windchill_c": 17.9,
              "windchill_f": 64.2,
              "heatindex_c": 17.9,
              "heatindex_f": 64.2,
              "dewpoint_c": 8.9,
              "dewpoint_f": 48.0,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.4,
              "gust_kph": 15.1,
              "uv": 5.0
            },
            {
              "time_epoch": 1692792000,
              "time": "2023-08-23 08:00",
              "temp_c": 18.4,
              "temp_f": 65.1,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 7.8,
              "wind_kph": 12.6,
              "wind_degree": 23,
              "wind_dir": "NNE",
              "pressure_mb": 1020.0,
              "pressure_in": 30.11,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 72,
              "cloud": 60,
              "feelslike_c": 18.4,
              "feelslike_f": 65.1,
              "windchill_c": 18.4,
              "windchill_f": 65.1,
              "heatindex_c": 18.4,
              "heatindex_f": 65.1,
              "dewpoint_c": 13.4,
              "dewpoint_f": 56.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.6,
              "gust_kph": 15.5,
              "uv": 5.0
            },
            {
              "time_epoch": 1692795600,
              "time": "2023-08-23 09:00",
              "temp_c": 20.7,
              "temp_f": 69.3,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 8.7,
              "wind_kph": 14.0,
              "wind_degree": 29,
              "wind_dir": "NNE",
              "pressure_mb": 1021.0,
              "pressure_in": 30.16,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 40,
              "cloud": 8,
              "feelslike_c": 20.7,
              "feelslike_f": 69.3,
              "windchill_c": 20.7,
              "windchill_f": 69.3,
              "heatindex_c": 20.7,
              "heatindex_f": 69.3,
              "dewpoint_c": 6.8,
              "dewpoint_f": 44.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 10.1,
              "gust_kph": 16.2,
              "uv": 6.0
            },
            {
              "time_epoch": 1692799200,
              "time": "2023-08-23 10:00",
              "temp_c": 22.2,
              "temp_f": 72.0,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 40,
              "wind_dir": "NE",
              "pressure_mb": 1021.0,
              "pressure_in": 30.15,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 35,
              "cloud": 7,
              "feelslike_c": 23.7,
              "feelslike_f": 74.7,
              "windchill_c": 22.2,
              "windchill_f": 72.0,
              "heatindex_c": 23.7,
              "heatindex_f": 74.7,
              "dewpoint_c": 5.9,
              "dewpoint_f": 42.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 10.3,
              "gust_kph": 16.6,
              "uv": 6.0
            },
            {
              "time_epoch": 1692802800,
              "time": "2023-08-23 11:00",
              "temp_c": 24.5,
              "temp_f": 76.1,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 5.8,
              "wind_kph": 9.3,
              "wind_degree": 42,
              "wind_dir": "NE",
              "pressure_mb": 1020.0,
              "pressure_in": 30.11,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 43,
              "cloud": 1,
              "feelslike_c": 25.2,
              "feelslike_f": 77.4,
              "windchill_c": 24.5,
              "windchill_f": 76.1,
              "heatindex_c": 25.2,
              "heatindex_f": 77.4,
              "dewpoint_c": 11.1,
              "dewpoint_f": 52.0,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.2,
              "gust_kph": 14.8,
              "uv": 6.0
            },
            {
              "time_epoch": 1692806400,
              "time": "2023-08-23 12:00",
              "temp_c": 24.4,
              "temp_f": 75.9,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 7.2,
              "wind_kph": 11.5,
              "wind_degree": 45,
              "wind_dir": "NE",
              "pressure_mb": 1020.0,
              "pressure_in": 30.12,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 29,
              "cloud": 6,
              "feelslike_c": 24.3,
              "feelslike_f": 75.7,
              "windchill_c": 24.4,
              "windchill_f": 75.9,
              "heatindex_c": 24.3,
              "heatindex_f": 75.7,
              "dewpoint_c": 5.2,
              "dewpoint_f": 41.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 8.3,
              "gust_kph": 13.3,
              "uv": 6.0
            },
            {
              "time_epoch": 1692810000,
              "time": "2023-08-23 13:00",
              "temp_c": 25.4,
              "temp_f": 77.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 5.8,
              "wind_kph": 9.4,
              "wind_degree": 54,
              "wind_dir": "NE",
              "pressure_mb": 1020.0,
              "pressure_in": 30.11,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 27,
              "cloud": 10,
              "feelslike_c": 24.7,
              "feelslike_f": 76.5,
              "windchill_c": 25.4,
              "windchill_f": 77.7,
              "heatindex_c": 24.7,
              "heatindex_f": 76.5,
              "dewpoint_c": 5.0,
              "dewpoint_f": 41.0,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.7,
              "gust_kph": 10.8,
              "uv": 7.0
            },
            {
              "time_epoch": 1692813600,
              "time": "2023-08-23 14:00",
              "temp_c": 26.4,
              "temp_f": 79.5,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 5.4,
              "wind_kph": 8.6,
              "wind_degree": 71,
              "wind_dir": "ENE",
              "pressure_mb": 1018.0,
              "pressure_in": 30.07,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 40,
              "cloud": 16,
              "feelslike_c": 26.4,
              "feelslike_f": 79.4,
              "windchill_c": 26.4,
              "windchill_f": 79.5,
              "heatindex_c": 26.4,
              "heatindex_f": 79.4,
              "dewpoint_c": 11.6,
              "dewpoint_f": 52.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.3,
              "gust_kph": 10.1,
              "uv": 7.0
            },
            {
              "time_epoch": 1692817200,
              "time": "2023-08-23 15:00",
              "temp_c": 26.4,
              "temp_f": 79.5,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 5.6,
              "wind_kph": 9.0,
              "wind_degree": 93,
              "wind_dir": "E",
              "pressure_mb": 1019.0,
              "pressure_in": 30.08,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 25,
              "cloud": 8,
              "feelslike_c": 25.3,
              "feelslike_f": 77.5,
              "windchill_c": 26.4,
              "windchill_f": 79.5,
              "heatindex_c": 25.3,
              "heatindex_f": 77.5,
              "dewpoint_c": 5.1,
              "dewpoint_f": 41.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.5,
              "gust_kph": 10.4,
              "uv": 7.0
            },
            {
              "time_epoch": 1692820800,
              "time": "2023-08-23 16:00",
              "temp_c": 26.3,
              "temp_f": 79.3,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 112,
              "wind_dir": "ESE",
              "pressure_mb": 1018.0,
              "pressure_in": 30.06,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 27,
              "cloud": 7,
              "feelslike_c": 25.3,
              "feelslike_f": 77.5,
              "windchill_c": 26.3,
              "windchill_f": 79.3,
              "heatindex_c": 25.3,
              "heatindex_f": 77.5,
              "dewpoint_c": 5.6,
              "dewpoint_f": 42.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 7.4,
              "gust_kph": 11.9,
              "uv": 7.0
            },
            {
              "time_epoch": 1692824400,
              "time": "2023-08-23 17:00",
              "temp_c": 24.4,
              "temp_f": 75.9,
              "is_day": 1,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 8.1,
              "wind_kph": 13.0,
              "wind_degree": 131,
              "wind_dir": "SE",
              "pressure_mb": 1017.0,
              "pressure_in": 30.03,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 47,
              "cloud": 78,
              "feelslike_c": 25.3,
              "feelslike_f": 77.6,
              "windchill_c": 24.4,
              "windchill_f": 75.9,
              "heatindex_c": 25.3,
              "heatindex_f": 77.6,
              "dewpoint_c": 12.4,
              "dewpoint_f": 54.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.2,
              "gust_kph": 14.8,
              "uv": 5.0
            },
            {
              "time_epoch": 1692828000,
              "time": "2023-08-23 18:00",
              "temp_c": 24.1,
              "temp_f": 75.4,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 139,
              "wind_dir": "SE",
              "pressure_mb": 1018.0,
              "pressure_in": 30.07,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 36,
              "cloud": 8,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 24.1,
              "windchill_f": 75.4,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 8.1,
              "dewpoint_f": 46.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 10.5,
              "gust_kph": 16.9,
              "uv": 6.0
            },
            {
              "time_epoch": 1692831600,
              "time": "2023-08-23 19:00",
              "temp_c": 22.6,
              "temp_f": 72.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 8.5,
              "wind_kph": 13.7,
              "wind_degree": 145,
              "wind_dir": "SE",
              "pressure_mb": 1018.0,
              "pressure_in": 30.07,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 42,
              "cloud": 9,
              "feelslike_c": 24.3,
              "feelslike_f": 75.7,
              "windchill_c": 22.6,
              "windchill_f": 72.7,
              "heatindex_c": 24.3,
              "heatindex_f": 75.7,
              "dewpoint_c": 9.0,
              "dewpoint_f": 48.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 11.0,
              "gust_kph": 17.6,
              "uv": 6.0
            },
            {
              "time_epoch": 1692835200,
              "time": "2023-08-23 20:00",
              "temp_c": 21.1,
              "temp_f": 70.0,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 7.6,
              "wind_kph": 12.2,
              "wind_degree": 149,
              "wind_dir": "SSE",
              "pressure_mb": 1017.0,
              "pressure_in": 30.02,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 67,
              "cloud": 52,
              "feelslike_c": 21.1,
              "feelslike_f": 70.0,
              "windchill_c": 21.1,
              "windchill_f": 70.0,
              "heatindex_c": 24.4,
              "heatindex_f": 76.0,
              "dewpoint_c": 14.7,
              "dewpoint_f": 58.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 10.5,
              "gust_kph": 16.9,
              "uv": 1.0
            },
            {
              "time_epoch": 1692838800,
              "time": "2023-08-23 21:00",
              "temp_c": 20.9,
              "temp_f": 69.6,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 6.9,
              "wind_kph": 11.2,
              "wind_degree": 159,
              "wind_dir": "SSE",
              "pressure_mb": 1019.0,
              "pressure_in": 30.09,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 49,
              "cloud": 11,
              "feelslike_c": 20.9,
              "feelslike_f": 69.6,
              "windchill_c": 20.9,
              "windchill_f": 69.6,
              "heatindex_c": 20.9,
              "heatindex_f": 69.6,
              "dewpoint_c": 9.9,
              "dewpoint_f": 49.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.6,
              "gust_kph": 15.5,
              "uv": 1.0
            },
            {
              "time_epoch": 1692842400,
              "time": "2023-08-23 22:00",
              "temp_c": 20.5,
              "temp_f": 68.9,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 6.0,
              "wind_kph": 9.7,
              "wind_degree": 163,
              "wind_dir": "SSE",
              "pressure_mb": 1019.0,
              "pressure_in": 30.09,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 51,
              "cloud": 8,
              "feelslike_c": 20.5,
              "feelslike_f": 68.9,
              "windchill_c": 20.5,
              "windchill_f": 68.9,
              "heatindex_c": 20.5,
              "heatindex_f": 68.9,
              "dewpoint_c": 9.9,
              "dewpoint_f": 49.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 8.7,
              "gust_kph": 14.0,
              "uv": 1.0
            },
            {
              "time_epoch": 1692846000,
              "time": "2023-08-23 23:00",
              "temp_c": 20.4,
              "temp_f": 68.7,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 181,
              "wind_dir": "S",
              "pressure_mb": 1018.0,
              "pressure_in": 30.06,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 74,
              "cloud": 100,
              "feelslike_c": 20.4,
              "feelslike_f": 68.7,
              "windchill_c": 20.4,
              "windchill_f": 68.7,
              "heatindex_c": 20.4,
              "heatindex_f": 68.7,
              "dewpoint_c": 15.6,
              "dewpoint_f": 60.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.9,
              "gust_kph": 11.2,
              "uv": 1.0
            }
          ]
        }
      ]
    }
  }